## 🧱 Model Training Pipelines

# Training a search ranking model involves collecting user interaction data, engineering features, training and
# validating models, and deploying them for inference. Azure provides a robust ecosystem to automate and scale this
# process.
#
# ### Pipeline Stages
#
# * Data Ingestion: Azure Data Factory or Synapse Pipelines to pull logs and metadata
# * Data Preprocessing: Azure Databricks or ML Pipelines to clean and normalize
# * Feature Engineering: Generate embeddings, CTR, freshness scores
# * Model Training: Use Azure ML with LightGBM, XGBoost, or BERT
# * Evaluation: Compute NDCG, MRR, Precision@K
# * Registration: Store models in Azure ML Registry
# * Deployment: Serve via Azure ML Online Endpoints or AKS
# * Monitoring & Retraining: Use Azure Monitor and automated ML pipelines

name: search-ranking-pipeline
description: Train and deploy a search ranking model using Azure ML
version: 1.0.0

jobs:
  preprocess_data:
    type: command
    component: azureml:preprocess_component@latest
    inputs:
      raw_data: azureml:search_logs_dataset@latest
    outputs:
      processed_data: azureml:processed_data_output
    compute: azureml:cpu-cluster

  feature_engineering:
    type: command
    component: azureml:feature_engineering_component@latest
    inputs:
      processed_data: preprocess_data.outputs.processed_data
    outputs:
      features: azureml:features_output
    compute: azureml:cpu-cluster

  train_model:
    type: command
    component: azureml:train_ranking_model@latest
    inputs:
      features: feature_engineering.outputs.features
    outputs:
      model_output: azureml:ranking_model_output
    compute: azureml:gpu-cluster

  evaluate_model:
    type: command
    component: azureml:evaluate_model_component@latest
    inputs:
      model: train_model.outputs.model_output
      test_data: azureml:test_dataset@latest
    outputs:
      evaluation_report: azureml:evaluation_output
    compute: azureml:cpu-cluster

  register_model:
    type: command
    component: azureml:register_model_component@latest
    inputs:
      model: train_model.outputs.model_output
      evaluation: evaluate_model.outputs.evaluation_report
    compute: azureml:cpu-cluster

settings:
  default_compute: azureml:cpu-cluster
  continue_on_step_failure: false